[package]
name = "ferris"
version = "0.1.0"
edition = "2018"

[dependencies]
volatile-register = "0"

[workspace]

[profile.dev]
panic = "abort"
opt-level = "s"
lto = true
debug-assertions = false
overflow-checks = false

[profile.release]
lto = true
